### PR TITLE
Validation added for City, State and Country for volunteer registration

### LINKED ISSUE #75: Validate City and Country
@vubo  I just saw yesterday's recording. I have one question, are we validating city and countries, when the user is entering the data in create event e.t.c?

If not, I feel its good to do that. There are packages that can achieve that for us.

### PR DESCRIPTION
**Pull request by saganshul**
Closes #75.

I have added a validation for city, state and country by using [django-cities-light](https://github.com/yourlabs/django-cities-light).

Basically, I have created Dependent Dropdown list for state and city field.

Please review.

Here are some screenshots.

screenshot from 2015-12-27 03-12-11
screenshot from 2015-12-27 03-11-46
screenshot from 2015-12-27 03-09-53
screenshot from 2015-12-27 03-09-30

### CODE REVIEW

**Comment by saganshul** [comment]
@tapasweni-pathak @willingc please review.

**Comment by tapasweni-pathak** [comment]
@saganshul The best way to reference a issue in your PR is to add "Fixes #number_of_issue". I have added in this one. The comments on the issue should be only about the discussion of that issue. So please try avoiding commenting on an issue, about something, which is not to discuss about it more.

Plus we get a notification when someone submits a pull request. :smile:

**Comment by saganshul** [comment]
I'm so sorry about that @tapasweni-pathak , will definitely take care of that in the future.

**Comment by tapasweni-pathak** [comment]
@saganshul No issues. Cool. ☺

**Comment by tapasweni-pathak** [comment]
@saganshul Thanks for the patience. 

These are too many changes to review in one go under one single commit. Please separate the changes. For ex : the changes you did in the test files, can go in one commit, where commit message can explain what you are doing in that commit. Ideally related changes should go in one commit or even changes of one file can go in one commit, nicely explaining what each commit is doing. How it is contributing to this big change that you want to have in VMS. 

Nice commit message help other contributors to track down the changes easily. Please do it and I'll merge and test the changes.

**Comment by tapasweni-pathak** [comment]
Closing this. Please reopen if rebased or create a fresh pull request.

**Pull request closed without merging**
