### PR TITLE
Notification

### PR DESCRIPTION
**Pull request by Anh3h**
Isolated issues concerning about from that with notification. This branch takes care of the issue with notification

### CODE REVIEW

**Comment by smarshy** [comment]
@Anh3h Please remove/modify the commits. You have tried to remove the changes by making more commits. The git reset head command might help you to do this.
If it seems complicated, make a new branch, keep only relevant changes in it (in this case changes for the notification pr) and create a new PR

**Comment by smarshy** [comment]
@Anh3h Please clean up this PR soon.

**Comment by tapasweni-pathak** [comment]
@Anh3h Are you still working on this?

**Comment by Anh3h** [comment]
No. Sorry but my machine had some issues and I lost track of so many things
including this

**Pull request closed without merging**
