### PR TITLE
Added fix to disable unauthorized access by volunteers

### PR DESCRIPTION
**Pull request by InfernoCoder**
Fixes issue #326 

In addition to the links mentioned in the issue, I've also fixed these urls -
1) `/volunteer/edit/` - Previously could be accessed by anyone
2) `/volunteer/add_hours/` - Previously could be accessed by anyone
3) `/volunteer/edit_hours/` - Previously could be accessed by anyone
4) `/shift/cancel/` - Previously showed an Http 403 page, fixed to show same error page as other ones.

Here is the screenshot -
screenshot from 2017-01-13 23-10-43

**PS: In this commit, administrators cannot see the volunteer restricted pages too _except shift sign-up page_. If this needs to be changed, please tell me.**

### CODE REVIEW

**Comment by InfernoCoder** [comment]
As usual, the tests never are successful the first time, uploading a fix soon.

**Comment by InfernoCoder** [comment]
There are some more test errors, I'll fix them by tomorrow

**Comment by smarshy** [comment]
@InfernoCoder There are conflicts in this PR. Please resolve them.

**Comment by InfernoCoder** [comment]
@smarshy Fixed the conflicts

**Comment by InfernoCoder** [comment]
This PR is closed and moved to #449 .

**Pull request closed without merging**
