### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by abhishekarya286**
# Description
I added a point in checklist that ensures that the PR title looks like" Fix #24: Updated PULL_REQUEST_TEMPLATE.md"

# Type of Change:
**Delete irrelevant options.**

- Quality Assurance
- Documentation

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds a guideline for the contributors)

# How Has This Been Tested?
image

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings

### CODE REVIEW

**Comment by abhishekarya286** [comment]
Hi @tapasweni-pathak @tonythomas01. Please review.

**Comment by prachi1210** [comment]
The PR template was finalised after a lot of discussion and is consistent across all repos. While I like your suggestion, please initiate a discussion for this on Slack

**Comment by abhishekarya286** [comment]
Great @prachi1210. Thanks for your review.

**Comment by MeepyMay** [comment]
Closing this for now. We're not making a change that affects all the repositories right now. I'll label as "OPEN LATER" when we talk about org-wide changes again. Right now, we have other higher priorities, such as GSoC.

**Pull request closed without merging**
