### PR TITLE
Add favicon to website.

### PR DESCRIPTION
**Pull request by Monal5031**
Closes https://github.com/systers/vms/issues/662

# Description
Changes include addition of favicon file to repo and corresponding HTML link for it.

# Type of Change:
**Delete irrelevant options.**

- Code

# How Has This Been Tested?
Tested directly by viewing the website, ss here:
favicon_added

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by kamsuri** [comment]
Looks good to me. I think you just need to keep the checked points and not the unchecked ones. I think @prachi1210 can guide you better here.

**Comment by Monal5031** [comment]
@kamsuri Deleted the unchecked points.
ping @prachi1210 Please review this PR :smile:

**Comment by tapasweni-pathak** [comment]
Flagging that there is no existing favicon file which would make this work.

**Comment by Monal5031** [comment]
@tapasweni-pathak Could you please elaborate?
I have added a favicon file in this PR, and shared a working snapshot with you.

**Comment by ayushgarg1804** [comment]
I think @tapasweni-pathak means that there is no existing favicon file which we have agreed to use for vms website.

**Comment by Monal5031** [comment]
Okay thanks @ayushgarg1804 ,
@tapasweni-pathak I've used the favicon of Systers website since this is a Systers project shouldn't it use the Systers favicon.

**Comment by MeepyMay** [comment]
@Monal5031 Can you update to this favicon? http://systers.io/

**Comment by MeepyMay** [comment]
@Monal5031 Can you update this to the new branding? 
favicon

**Comment by Monal5031** [comment]
Yeah sure @MeepyMay , away from keyboard atm will do it asap. :)

**Comment by MeepyMay** [comment]
Thank you~

**Pull request merged**
