### PR TITLE
Datepicker admin for Create Event

### PR DESCRIPTION
**Pull request by vubo**
Issue https://github.com/systers/vms/issues/59

I used [Datepicker for the date range](https://jqueryui.com/datepicker/#date-range).

@willingc @tapasweni-pathak I have a couple of questions:
- I added a new javascript function for the datepicker to the file *vms/vms/static/vms/jquery-custom/activate-datepicker.js* Is it OK?
- Actual date format: MM/DD/YYYY Is it suitable? Or is DD/MM/YYYY better?

dp

### CODE REVIEW

**Comment by willingc** [comment]
@vubo Thanks for submitting :)

Front end code is my weakness so I'm going to leave this open for @tapasweni-pathak to comment as well.

I think for now the date field as you have it MM/DD/YYYY is fine. It would be a good idea to see what Portal does for data and/or ask Rose. Though simple enough to change if needed.

Since it is a data entry field, we should make sure that we are preventing XSS vulnerabilities and that we properly handle CSRF.

**Comment by vubo** [comment]
@willingc thank you!

> Since it is a data entry field, we should make sure that we are preventing XSS vulnerabilities and that we properly handle CSRF.

How can I do this in Django? Do you have any tips :blush: ?

I added one more commit https://github.com/vubo/vms/commit/fce20dffce8358a889cb8725454296b5bc404c3a to this PR.  This is the same datepicker but for admin create job. Should I do something else?

**Comment by willingc** [comment]
Let's start with the Django docs: https://docs.djangoproject.com/en/1.8/ref/csrf/
It would be good to keep as much security functionality within Django and not write anything that would override the Django security. Down the road that would be a maintenance nightmare.

I think that @Nerdylicious already handled the CSRF on the existing forms by having it inside the Post div tag actions. 

I would double check the docs and let me know what you think.

**Comment by tapasweni-pathak** [comment]
@vubo it looks great. :)

@willingc  :+1: for CSRF and  preventing XSS vulnerabilities. It is important.

@exploreshaifali What format does Systers Portal uses for date, is it MM/DD/YYYY or DD/MM/YYYY?

**Comment by willingc** [comment]
@vubo Thanks! If you wouldn't mind squashing the commits, I'm happy to merge.

@tapasweni-pathak Thanks for reviewing :)

**Comment by tapasweni-pathak** [comment]
@willingc I asked @exploreshaifali about the format Systers Portal uses. 

She said : "Python default date formate is - YYYY,MM,DD. Same default django.db.models.DateField use, for portal meetup we will use same."

So do you think we should change ours or do you want to keep the current one?

**Comment by vubo** [comment]
@willingc @tapasweni-pathak thank you! I created a new PR https://github.com/systers/vms/pull/63 for this issue with the squashed commits.

**Pull request closed without merging**
