### PR TITLE
Fixed edit job date validity

### PR DESCRIPTION
**Pull request by AaskaShah**
Before:
 When a job was created,it didn't allow start date and end date to be outside event dates.
 But when the job was edited,it showed no error for dates outside that of event dates.

Now : 
 It shows error message as in create job page for edit page if dates selected were not valid.

Please review and suggest changes.

### CODE REVIEW

**Comment by AaskaShah** [comment]
Fixed #192

**Comment by tapasweni-pathak** [comment]
Thanks for the work @AaskaShah. :+1:

**Comment by AaskaShah** [comment]
There is a slight change in the code for not storing the wrong edited dates.I apologize for that. Shall I do it ?

**Comment by tapasweni-pathak** [comment]
@AaskaShah I didn't get you. :( 

Can you explain it more?

**Comment by AaskaShah** [comment]
```
if(start_date_job>=start_date_event and end_date_job<=end_date_event):
                    job = form.save(commit=False)
                    if event:
                        job.event = event
                    else:
                        raise Http404
                    job_to_edit.save()
                    job.save()
                    return HttpResponseRedirect(reverse('job:list'))
```

This is the correct code, job_to_edit.save() should be in the if statement.

**Comment by AaskaShah** [comment]
Should I send a PR about the same ?

**Comment by tapasweni-pathak** [comment]
@AaskaShah Can you please explain what do you mean by *not storing the wrong edited dates*?

**Comment by AaskaShah** [comment]
After one edits the dates which does not lie in between the event dates,the error message is shown up, but the dates are still stored and are reflected on the page.

**Comment by AaskaShah** [comment]
Should I send PR to solve this bug? @tapasweni-pathak

**Comment by tapasweni-pathak** [comment]
Sure @AaskaShah. Raise an issue if there is none till now and then reference it in the PR description.

**Comment by AaskaShah** [comment]
This bug dos not show up now, must have been fixed in any of the merged PRs

**Pull request merged**
