### PR TITLE
Fixes the Volunteer Signup form.

### LINKED ISSUE #336: Misplaced if-else clause in volunteer sign up template
The error message should be displayed if there are errors. The if else statements seem to be switched in this [line](https://github.com/systers/vms/blob/develop/vms/registration/templates/registration/signup_volunteer.html#L381) onwards for resume field on volunteer registration form

### PR DESCRIPTION
**Pull request by necessary129**
Fixes #336

### CODE REVIEW

**Comment by necessary129** [comment]
@smarshy Was the second commit the thing that you meant? :smiley:

**Comment by smarshy** [comment]
@necessary129 yes, good that you updated the tests too :)

**Comment by smarshy** [comment]
@tapasweni-pathak There was only one instance of this task for GCI. Other students wouldn't be working on this.

**Comment by tapasweni-pathak** [comment]
@smarshy I didn't get the context here. Am I required to do something here? 😕

**Comment by smarshy** [comment]
@tapasweni-pathak I added that in case it looks okay to you and you want to merge it. There wouldn't be more submissions for this task as all instances are used up.

**Pull request merged**
