### PR TITLE
Fixed issue of drop downs and added docstrings

### PR DESCRIPTION
**Pull request by mish24**

### CODE REVIEW

**Comment by smarshy** [comment]
@mish24 Reference the issue you are trying to fix. Also, please check your commits. This is a small change and they are too many in number; You have repeated changes in some of these commits.

**Comment by smarshy** [comment]
@mish24 I cannot see any docstring in the changes. Also, is #438 is a duplicate of this PR? I see the same changes there. Also, add issue number, fix the title and add a description which details your changes
If this PR is outdated, please close it.

**Comment by tapasweni-pathak** [comment]
@mish24 Are you still working on this?

**Comment by tapasweni-pathak** [comment]
@mish24 Please reopen if you plan to continue working on this.

**Pull request closed without merging**
