### PR TITLE
Added dropdown options for signed in users instead of separate links

### LINKED ISSUE #266: Navigation bar should show dropdown with user actions instead of separate links
The current design has the navigation bar, after sign-in as: 
image

This should look better if we can have something like 
selection_056

with the logged in user name  + a drop down.

### PR DESCRIPTION
**Pull request by amruthasangeeth**
Fix #266

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
@amruthasangeeth Some unnecessary commits are coming up, can you please clean your pull request?

**Comment by amruthasangeeth** [comment]
I have cleaned the unwanted commits.

**Comment by tapasweni-pathak** [comment]
@amruthasangeeth One is still there. Can you remove that too?

**Comment by amruthasangeeth** [comment]
I have removed all other commits

**Comment by tapasweni-pathak** [comment]
Thanks for the work @amruthasangeeth. :)

**Pull request merged**
