### PR TITLE
Changes in organisations dynamically reflected in signup form

### LINKED ISSUE #652: Organisation name not updated in signup form.
## Description
As an admin,
If I edit the Organisation name the name is not updated in the SignUp form for new volunteers.

## Mocks
screen shot 2018-03-05 at 8 28 47 pm

screen shot 2018-03-05 at 8 29 25 pm

### Update [Required]
- [ ] Name of Organization should be updated in the SignUp form.
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by sammy1997**
# Description
Editing or adding new organizations are reflected in the signup form. There is no need to restart the server.

Fixes #652 

# Type of Change:
- Code
- Bug fix (a non-breaking change which fixes an issue)

# How Has This Been Tested?
issue652_1
issue652_2
issue652_3

# Checklist:

- [ ] My PR follows the style guidelines for this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Any dependent changes have been merged 
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sammy1997** [comment]
@m-murad @tapasweni-pathak @kamsuri  Please review this.

**Comment by abhishekarya286** [comment]
Nice work @sammy1997. Thanks for your contribution. @prachi1210, please merge this.

**Comment by MeepyMay** [comment]
@sammy1997 Did you write tests? The coverage went down.

**Comment by m-murad** [comment]
@sammy1997 
please add a test and we will be good to merge this PR.

**Comment by sammy1997** [comment]
Sorry for the late reply, was swamped with university work and exams :( . I will add tests soon @m-murad @MeepyMay .

**Comment by sammy1997** [comment]
@anjali-dhanuka I had the same doubt as you had asked about. The tests are all commented out. Where do we need to add the tests then?

**Comment by anjali-dhanuka** [comment]
@Monal5031 Can u please guide @sammy1997

**Comment by Monal5031** [comment]
@anjali-dhanuka I've solved the selenium issue but there are some other errors rising after upgrading the selenium versions. Also as the test structure will be changing quite a bit (all the tests will be moved to a different dir in root of project) so we'd have to wait a bit. is that okay?

**Comment by anjali-dhanuka** [comment]
That's fine @Monal5031 but Please do the same before 17th May(the deadline you mentioned to May).

**Comment by anjali-dhanuka** [comment]
@sammy1997 Will you be writing tests for the PR @Monal5031 is done with all the tests?

**Comment by anjali-dhanuka** [comment]
Since @sammy1997 is not responding closing this for now

**Pull request closed without merging**
