### PR TITLE
Updated Readme

### LINKED ISSUE #882: Updating Readme with the Installation steps through virtual environment.
## Description
As a developer,
I need to add Installation steps through virtual environment as the installation steps through docker as mentioned in the README are using python 2.7 instead of python 3.6,

### Update [Required]
- [ ] Installation steps through virtual environment should be added in README.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by muskan6769**
Changed the link to the Installation guide.

# Description
The new installation guide link describes the installation steps with the use of virtual environment.

Fixes #882 

# Type of Change:
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# Checklist:

- [x] My PR follows the style guidelines of this project
- [x] I have made corresponding changes to the documentation

### CODE REVIEW

**Comment by Monal5031** [comment]
@muskan6769  can you repush your commits or restart the build on this PR? The failure is not related to your changes but still they need to pass.

**Comment by Monal5031** [comment]
@muskan6769 changes look good, just squash your commits so we can merge this

**Comment by muskan6769** [comment]
@Monal5031 now there are two commits,do I need to squash that "merge pull request commit also"?

**Comment by Monal5031** [comment]
Yes, please only 1 commit per PR

**Comment by muskan6769** [comment]
@Monal5031 All the checks have passed. Please have a look.

**Pull request merged**
