### PR TITLE
Removed unreachable lines of code in vms/utils

### LINKED ISSUE #627: Unreachable statements in vms/utils.py
## Description
The code vms/utils.py is scattered with unreachable return statements( statements that won't be executed in any case). The code could be cleaned up. 
## Mocks
screenshot from 2018-02-17 14-14-00
screenshot from 2018-02-17 14-14-05

## Acceptance Criteria
- [ ] Remove unnecessary lines of unreachable code 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
5-10 mins

@MeepyMay @tonythomas01 @tapasweni-pathak please review this

### PR DESCRIPTION
**Pull request by sammy1997**
# Description
Removed unreachable render statements from utils.py to cleanup the code
 
Fixes #627 
# Type of Change:
- Code
**Code/Quality Assurance Only**

# How Has This Been Tested?
Code quality related change, hence no testing required.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

@tapasweni-pathak @MeepyMay @tonythomas01 Please review this

### CODE REVIEW

**Comment by tonythomas01** [comment]
I am really surprised that the three functions have the very same exact function body. Can you fix it somehow ? Like, fixing the calls to probably just one single function ?

**Comment by sammy1997** [comment]
@tonythomas01 Ok. I will look into this. Certainly there is a lot common between these functions

**Comment by sammy1997** [comment]
@tonythomas01 @tapasweni-pathak I have removed unneccessary function as suggested by @tonythomas01 . Please review this PR.

**Comment by sammy1997** [comment]
@tapasweni-pathak @prachi1210 Please review this

**Comment by sammy1997** [comment]
@kamsuri @tapasweni-pathak Please review this.

**Comment by tonythomas01** [comment]
Looks better. +1

**Comment by sammy1997** [comment]
@tapasweni-pathak @ramitsawhney27 @Buddhiprabha @kamsuri @abhishekarya286

**Pull request merged**
