### PR TITLE
Job editing now shows shift dates

### LINKED ISSUE #396: Simplify editing of job
While editing a job, there is a check to ensure that the included shifts are not falling outside the new date range. It may be helpful to show the range of dates while allowing the user to edit the form.

### PR DESCRIPTION
**Pull request by PhoeniXkrypT**
Closes #396 
    GH link : https://github.com/systers/vms/issues/396
    - job/services.py : Add get_job_shift_dates_distinct()
    - job/views.py    : JobUpdateView.get_object() modified to use
                        get_job_by_id.
                        JobUpdateView.get_context_data modified to set
                        shift dates in context.
    - templates/job/edit.html : Modified to display shift dates.

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
@PhoeniXkrypT Travis is failing. You need to correct the issues.

**Comment by smarshy** [comment]
@PhoeniXkrypT Please fix the issues in the build.

**Comment by tapasweni-pathak** [comment]
@PhoeniXkrypT Are you still working on this?

**Comment by tapasweni-pathak** [comment]
@PhoeniXkrypT Please reopen if you plan to continue working on this.

**Pull request closed without merging**
