### PR TITLE
shift end time greater than start time

### LINKED ISSUE #194: Shift can start and end at the same time
I created a shift that started and ended at the same time. No errors were reported and the creation was successful which is incorrect.

### PR DESCRIPTION
**Pull request by AaskaShah**
fixed #194 

Please review and suggest changes.

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
@AaskaShah Can you please resolve the merge conflicts in this pull request?

**Comment by AaskaShah** [comment]
Done :)

**Comment by tapasweni-pathak** [comment]
@AaskaShah Please rebase your changes. A merged commit which says *merge conflict resolved* will not help if someone wants to track down the changes by going through all the commits.

One should always write good commit messages which can help to understand the change and to track down the diffs easily.

**Comment by AaskaShah** [comment]
I would surely take care of the commit messages next time. Thank you :)
Is there still anything that needs to be changed?

**Comment by tapasweni-pathak** [comment]
@AaskaShah np. :)

There is some mess here, now. :(

If you see your two commits, one is having changes it should not. Can you please look into it and rebase? Let me know if you face any issues.

**Pull request closed without merging**
