### PR TITLE
Removing importing of all modules using *. It closes issue #379

### LINKED ISSUE #379: Remove all 'import *' from code
In  my opinion using `from module import *` is not good.

> ```
> Because it puts a lot of stuff into your namespace (might shadow some other object from previous import and you won't know about it).
> 
> Because you don't know exactly what is imported and can't find place from what module certain thing was imported easily (readability).
> 
> Because you can't use cool tools like pyflakes to detect statically errors in your code.
> ```

Source: http://stackoverflow.com/questions/2386714/why-is-import-bad
https://pythonconquerstheuniverse.wordpress.com/2011/03/28/why-import-star-is-a-bad-idea/

Few examples in vms code:
https://github.com/systers/vms/blob/aa75b55bca85196a270e5f697d10b26b85defdf5/vms/shift/views.py#L7

aa75b55bca85196a270e5f697d10b26b85defdf5

### PR DESCRIPTION
**Pull request by josejibin**
Removing importing of all modules using *. It closes issue #379 

* Remove all 'import *' from code
* Remove unused imports

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
@josejibin Can you please fix the conflicts?

**Comment by josejibin** [comment]
@tapasweni-pathak 
Can you please guide me to resolve the conflicts?

**Comment by tapasweni-pathak** [comment]
@josejibin [These](https://help.github.com/articles/resolving-a-merge-conflict-on-github/) [guides](https://github.com/AgileVentures/MetPlus_PETS/wiki/Resolving-Pull-Request-merge-conflicts) will help. Quick fix but not the right way is to close this pull request and create a new one with these changes.

**Comment by tapasweni-pathak** [comment]
@josejibin Please reopen if you plan to continue working on this.

**Pull request closed without merging**
