### PR TITLE
Removed spelling error in README.md

### LINKED ISSUE #611: Spelling error in README.md
## Description

In README **speak peek** can be changed to **sneak peek**.

## Mocks
screen shot 2018-02-11 at 3 14 52 pm

### Update [Required]
- [ ] README.md

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
 2 minutes

### PR DESCRIPTION
**Pull request by PrajwalM2212**
# Description

Changes **speak peek** into **sneak peek** in README.md

Fixes #611 

# Type of Change:
**Delete irrelevant options.**

- Documentation

**Code/Quality Assurance Only**

- This change requires a documentation update (software upgrade on readme file)

# How Has This Been Tested?
Change in README.md . Does not require tests.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abhishekarya286** [comment]
Thanks @PrajwalM2212 for your work. **LGTM**. **PTAL** @tonythomas01.

**Comment by abhishekarya286** [comment]
Hi @prachi1210. This seems fine to me. Kindly merge it.

**Comment by ayushgarg1804** [comment]
A commit already exits doing the same thing https://github.com/systers/vms/commit/7755e64e244e9f6e4a5c87d74269b011df8baa06

**Comment by MeepyMay** [comment]
@ayushgarg1804 mentioned a commit that fixes this problem. Closing PR. Thank you for your work.

**Pull request closed without merging**
