### PR TITLE
Migrated authentication application from FBV to CBV

### PR DESCRIPTION
**Pull request by amruthasangeeth**
Migrated authentication application from CBV using Django's auth views. It used function based views for  login and logout process earlier. The number of lines of code are reduced using Django's built in auth views.

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
@amruthasangeeth Two unnecessary commits are present in this pull request, can you please clean it up?

**Comment by amruthasangeeth** [comment]
I have cleaned the unwanted commits

**Comment by tapasweni-pathak** [comment]
@amruthasangeeth This now has conflicts, can you please resolve them?

**Comment by tapasweni-pathak** [comment]
@amruthasangeeth Please incorporate the suggestion I gave [here](https://github.com/systers/vms/issues/288#issuecomment-223458651).

**Comment by amruthasangeeth** [comment]
@tapasweni-pathak Can you explain this?

**Comment by tapasweni-pathak** [comment]
@amruthasangeeth I didn't get you. :( What do you want me to explain?

**Pull request closed without merging**
