### PR TITLE
fix: updated logo from systers to anitab.org

### LINKED ISSUE #982: Remove Systers Logo
## Description
As a user,
I need to remove Systers logo,
so that I can see only AnitaB.org logo.

## Mocks
systersanitabvms

### Update [Required]
- [ ] Removed Systers logo 

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hour

### PR DESCRIPTION
**Pull request by divyanshugit**
**Description**
Deleted previous logo and added a new logo for Volunteer Management System

Fixes #982

**Type of Change:**

-  User Interface

**Checklist**

- [x] Removed Systers logo

- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by yashshah2820** [comment]
@divyanshugit did you added the Anitab.org logo?

**Comment by divyanshugit** [comment]
**Previously**

previous logo
**After Update**
updated logo

**Review by theyashshahs — DISMISSED** [review]

**Review by mayburgos — DISMISSED** [review]
@divyanshugit can you fix the logo so it's not "squashed" vertically?

**Comment by divyanshugit** [comment]
@mayburgos , @yashshah2820 can you review once !

**Comment by isabelcosta** [comment]
@divyanshugit can you please add to the PR description how the logo will look like now on the website with your change?

**Comment by divyanshugit** [comment]
@isabelcosta I have already added that you can preview it https://github.com/anitab-org/vms/pull/1000#issuecomment-664002403

**Review by isabelcosta — APPROVED** [review]
Looks good @divyanshugit !
I hope we can get 1 more approval and a test and then merge it :)

**Review by rpattath — APPROVED** [review]
LGTM

**Review by theyashshahs — APPROVED** [review]

**Comment by gaurivn** [comment]
@divyanshugit, can you pls update the branch from where you sent the PR. It's most preferable to not send PRs from develop too, it's fine for now, but next time onwards do send from a branch different from develop.

**Comment by divyanshugit** [comment]
@gaurivn  Okay, I will keep this in my mind from the next time onwards. Thanks for the advice.

**Comment by devkapilbansal** [comment]
@vj-codes @rpattath this issue is already resolved. Consider closing this and linked issue

**Comment by isabelcosta** [comment]
@devkapilbansal solved in another issue? If that is the case, could you please link it in a comment here. If you mean, merge this, let me know and I can proceed with merging.

**Comment by devkapilbansal** [comment]
> @devkapilbansal solved in another issue? If that is the case, could you please link it in a comment here. If you mean, merge this, let me know and I can proceed with merging.

Sorry my bad. Commented on wrong issue

**Review by devkapilbansal — APPROVED** [review]

**Pull request closed without merging**
