### PR TITLE
Volunteer profile: Restrict file type in resume

### PR DESCRIPTION
**Pull request by kriti21**
The upload_resume field in profile form accepts
files having extensions like .pdf, .doc, and .docx only.

Closes https://github.com/systers/vms/issues/565

# Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by anjali-dhanuka** [comment]
@kriti21 Which file type did u try?

**Comment by kriti21** [comment]
@anjali-dhanuka this is part of some other issue I have been working on. Resume_Upload is fine for all required file types.

**Comment by anjali-dhanuka** [comment]
@kriti21 can u explain?

**Comment by kriti21** [comment]
https://github.com/systers/vms/pull/556 This would help @anjali-dhanuka

**Comment by kriti21** [comment]
Added a new PR https://github.com/systers/vms/pull/614 that solves conflict issues.

**Pull request closed without merging**
