### PR TITLE
Gsoc 18 commits

### PR DESCRIPTION
**Pull request by anjali-dhanuka**
# Description
Merging Infra commits with code branch

# Type of Change:
- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by Monal5031** [comment]
Are we merging infra commits to code in this? :thinking:

**Comment by ayushgarg1804** [comment]
Yes @Monal5031, its just that (pulling majorly as hash is not changing). I think @anjali-dhanuka made this PR since it was getting difficult for @abhishekarya286 to review other PRs.

**Comment by anjali-dhanuka** [comment]
Done @ayushgarg1804 @Monal5031 Can you please merge this.

**Comment by Monal5031** [comment]
@anjali-dhanuka another PR got merged today can you please pull that as well?

**Comment by anjali-dhanuka** [comment]
Hi @Monal5031 Done with adding the PR too. @abhishekarya286 @ayushgarg1804 Can you please review, and merge this. Other Prs will be easy to review after this gets merged.

**Comment by ayushgarg1804** [comment]
@anjali-dhanuka Please fix travis-ci/pr build fail

**Comment by Monal5031** [comment]
@ayushgarg1804 Those are because of the registration app which got merged, retention tests are failing I've looked into some solutions if not fixed I'll comment them out and document them. Issue is already open for it. #787

**Comment by Monal5031** [comment]
@anjali-dhanuka retention test has been merged, please pull those commits.

**Comment by anjali-dhanuka** [comment]
Hi @ayushgarg1804 @abhishekarya286 @kamsuri Added that PR, please review

**Pull request merged**
