### PR TITLE
Added drop downs for administrator and docstrings, updated shift views

### PR DESCRIPTION
**Pull request by mish24**
Fixes issue #382  and #383. 
@smarshy Thanks for looking! Please review these.

### CODE REVIEW

**Comment by mish24** [comment]
#392 and #379 also fixed

**Comment by smarshy** [comment]
@mish24 There are too many changes in this PR. Please break them.

#392 - This is fixed already. Remove changes for this
#379 - You should do this across many files and then raise a PR. I had commented the same on the issue.
#383, #382 - these issues were for volunteer report, not admin.

**Comment by tapasweni-pathak** [comment]
@mish24 Can you please fix the conflicts and break these changes in separate pull request? It is better to submit the change for one issue in one pull request.

**Comment by mish24** [comment]
@tapasweni-pathak I'm so sorry I was caught up with GSoC work and didn't get time. I'll surely fix them as soon as I can and make the changes as you requested.

**Comment by tapasweni-pathak** [comment]
@mish24 Please reopen if you plan to continue working on this.

**Pull request closed without merging**
