### PR TITLE
Update README.md file

### PR DESCRIPTION
**Pull request by vubo**
https://github.com/systers/vms/issues/17

### CODE REVIEW

**Comment by willingc** [comment]
@vubo Would you mind resubmitting this PR to the `develop` branch? Thanks! It will make my life easier since there is not a simple way to move PRs from one branch to another.

**Comment by vubo** [comment]
@willingc Unfortunately, I can not do it:

pr

**Comment by willingc** [comment]
@vubo No worries. I'll take care of this. Thanks for giving it a shot :)

**Comment by vubo** [comment]
@willingc Thank you Carol :)

**Pull request merged**
