### PR TITLE
Replace 'None' by placeholder in  resume upload field of volunteer sign up form

### LINKED ISSUE #602: Replace 'None'  by placeholder in in resume upload field of volunteer sign up form
## Description
Resume upload field in sign up form should have a placeholder

## Mocks
image
image

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

### PR DESCRIPTION
**Pull request by anjali-dhanuka**
# Description
Stopped display of resume if it is 'None'

Fixes #602 

# Type of Change:
- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
image

# Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anjali-dhanuka** [comment]
@tonythomas01 @tapasweni-pathak Please review.

**Comment by anjali-dhanuka** [comment]
@tonythomas01 @tapasweni-pathak Please review the pr.

**Comment by abhishekarya286** [comment]
Hi @anjali-dhanuka. Thanks for your work. **LGTM**. @tapasweni-pathak @tonythomas01. **PTAL**

**Comment by mohitkyadav** [comment]
@anjali-dhanuka There is a typo in PR template.
MEntion the issue number, it should be #{issue number}.

**Comment by anjali-dhanuka** [comment]
@mohitkyadav Thanks for pointing this out. Done!

**Pull request merged**
