### PR TITLE
[WIP] Removing hardcoded dates

### PR DESCRIPTION
**Pull request by mish24**

### CODE REVIEW

**Comment by smarshy** [comment]
@mish24 The build is failing; Please fix the errors. Also, reference the issue you are fixing and make the commit messages clearer

**Comment by tapasweni-pathak** [comment]
@mish24 Are you still working on this?

**Comment by mish24** [comment]
@tapasweni-pathak I will resume my work on this. Sorry for the delay!

**Comment by tapasweni-pathak** [comment]
@mish24 :wave:

**Pull request closed without merging**
