### PR TITLE
Checking for logged hours to be between scheduled shift hours

### LINKED ISSUE #226: Log hours needs to be between scheduled shift hours
If a one is assigned a shift from 14:00 to 18:00 , one is able to log hours in that shift from 19:00 to 20:00.
Also if the scheduled hours of shifts were shown during log hours,it would be helpful. 
Currently it is like this:
screenshot from 2016-02-18 11 52 28

If this needs to be done , can I go ahead and work on it?

### PR DESCRIPTION
**Pull request by AaskaShah**
Checks for validity of logged hours both during logging hours and editing logged hours.
Fixes #226

### CODE REVIEW

**Comment by willingc** [comment]
@AaskaShah Please fix the Python spacing errors for PEP8 formatting. Python indentation is 4 spaces per level. You may push your changes to this branch. 

If you need a code editor to see the spacing, Atom is free and cross platform supported.

**Comment by AaskaShah** [comment]
Done :)

**Comment by tapasweni-pathak** [comment]
@AaskaShah This has conflicts now, can you please fix it?

**Comment by AaskaShah** [comment]
@tapasweni-pathak ,  fixed conflicts :)

**Comment by tapasweni-pathak** [comment]
@AaskaShah This again got conflicts, can you please fix them?

**Comment by tapasweni-pathak** [comment]
@AaskaShah When you resolve conflicts, you need to rebase the changes. If I merge this PR, not needed cleanup commits will also go in commit history. Changes should be trackable from the commit log. Please rebase and update the PR. 

If you get stuck, we are happy to help. :)

**Comment by AaskaShah** [comment]
I rebased and resolved conflicts, also squashed the commits into one. Have I done correct ?

**Comment by tapasweni-pathak** [comment]
Thanks for the work @AaskaShah. :+1:

**Pull request merged**
