### PR TITLE
Fixed shifts save error and appropriate return to job shifts after save operation

### PR DESCRIPTION
**Pull request by softcoder32**
shift saving gave 404 error when shift_id was not same as job_id and after saving did not return to the appropriate job shifts because a wrong job_id was sent

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
@softcoder32 This has conflicts now, can you please fix them?

**Comment by softcoder32** [comment]
I hope to have fixed the conflict, it seems previous code has formating issues and when fixed conflicts with original code. don't know why!

**Comment by tapasweni-pathak** [comment]
@softcoder32 You need to do a fresh pull and rebase your changes and then you can force push to update this pull request. Let us know if you face any issues.

**Comment by softcoder32** [comment]
Okay @tapasweni-pathak , never done rebasing but let me give it a try. thanks

**Pull request closed without merging**
