### PR TITLE
It closes #379 [WIP]

### LINKED ISSUE #379: Remove all 'import *' from code
In  my opinion using `from module import *` is not good.

> ```
> Because it puts a lot of stuff into your namespace (might shadow some other object from previous import and you won't know about it).
> 
> Because you don't know exactly what is imported and can't find place from what module certain thing was imported easily (readability).
> 
> Because you can't use cool tools like pyflakes to detect statically errors in your code.
> ```

Source: http://stackoverflow.com/questions/2386714/why-is-import-bad
https://pythonconquerstheuniverse.wordpress.com/2011/03/28/why-import-star-is-a-bad-idea/

Few examples in vms code:
https://github.com/systers/vms/blob/aa75b55bca85196a270e5f697d10b26b85defdf5/vms/shift/views.py#L7

aa75b55bca85196a270e5f697d10b26b85defdf5

### PR DESCRIPTION
**Pull request by josejibin**
It is a work in progress PR. Need to test all views.
* Remove all 'import *' from code
* Remove unused imports
* Sort imports using isort(https://docs.djangoproject.com/en/dev/internals/contributing/writing-code/coding-style/#imports)

### CODE REVIEW

**Comment by josejibin** [comment]
I think I missed some git flow. 
This is what I followed
  * forked repository
  * cloned the repository and created a branch `issue-379`
  * worked on that branch and committed
  *  pulled from upstream(git@github.com:systers/vms.git) development branch
  * tried to resolve conflicts and committed changes

can you guide what to do now?

**Comment by smarshy** [comment]
@josejibin I think the rebasing process wrong. You should fetch your upstream to your develop branch and merge it - that would sync your fork, but you shouldn't get any conflicts here. And then rebase your new branch - this is where you might need to resolve conflicts.

**Comment by anweshknayak** [comment]
@smarshy won't it be a good idea if we split this into different PRs ? Humongous changes on a single PR may not be a good idea keeping in mind case if you may need to revert back at some point :) and https://landscape.io/ this helps to keep in check

**Comment by josejibin** [comment]
@smarshy  
thank you. But I couldn't fix the git. So I worked on a new branch submitted a new PR. 
closing this one.

**Pull request closed without merging**
