### PR TITLE
Logging hours (adding & editing) shows shift time

### LINKED ISSUE #409: Simplify logging of hours
While entering/editing hours in the log hours form, there is no helper information provided about the start and end time of the shift.

### PR DESCRIPTION
**Pull request by PhoeniXkrypT**
Closes #409 
GH link : https://github.com/systers/vms/issues/409
- views.py : AddHoursView and EditHoursView modified to pass
             shift and volunteer shift values to render.
- templates/shift/add_hours.html : Modify to display shift hours.
- templates/shift/edit_hours.html : Modify to display shift and logged
                                    shift hours.

### CODE REVIEW

**Comment by PhoeniXkrypT** [comment]
@smarshy Did you mean that the shift time doesn't have to be shown in the page (i.e in the HTML)?

**Comment by PhoeniXkrypT** [comment]
I am working on the suggested changes.

**Comment by smarshy** [comment]
@PhoeniXkrypT Sorry for the delay in responding. 
Both the admin and volunteer can add/edit hours. You have made the changes for the volunteer add/edit hours form. The admin has different forms, please make the same changes for them too.

**Comment by PhoeniXkrypT** [comment]
@smarshy 'coverage/coveralls' shows one failed check in views.py but the build is successful. Is this fine or something has to be done?

**Comment by tapasweni-pathak** [comment]
@PhoeniXkrypT Thanks for the pull request! Merging it. :+1:

**Pull request merged**
