### PR TITLE
added country drop down box for event creation

### PR DESCRIPTION
**Pull request by varunnaganathan**

### CODE REVIEW

**Comment by vubo** [comment]
@varunnaganathan could you include only one relevant commit in this PR? I see 4 commits now. And please always describe your PR, so everyone can understand, what you did.

**Comment by varunnaganathan** [comment]
So basically i used an existing application called django-countries to get the data for all the ISO 3166-1 countries as choices.The previously existing country field was modified to a drop down country menu for users to select the required country for the event.Also modified the edit page of an event to display previously selected country and modify it accordingly.

**Comment by vubo** [comment]
@varunnaganathan I mean your PR description.
image

**Comment by varunnaganathan** [comment]
I have opened a new pull request with a single commit and a proper description https://github.com/systers/vms/pull/165
I would be closing this pull request.
I am new to open source contribution.sorry for the confusion.

**Comment by vubo** [comment]
@varunnaganathan it is ok :+1: the goal is that everyone can review your PRs.

**Pull request closed without merging**
