### PR TITLE
event id added for schema to identify any event uniquely

### LINKED ISSUE #657: Primary key for Events
## Description
As a user
I need to include the internal incorporation of a field to the event form that can act as a primary key, say an event id,
so that I  can separate an event with the same name by the same organisation in 2 different cities/locations as they would be organised by different branches. An even better solution would be to simply include an event id and add that to the key for the schema to identify any event uniquely. This is with reference to the resolution of problems in the issue #627.

### Update [Required]
- [ ] [Add attribute for primary key for the event form]
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
[0.25] hours

### PR DESCRIPTION
**Pull request by anjali-dhanuka**
# Description
Unique constraint on event name removed, thus I can separate an event with the same name by the same organisation in 2 different cities/locations as they would be organised by different branches. 

Fixes #657 

# Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
screenshot from 2018-04-04 02-51-01
screenshot from 2018-04-04 02-50-54

# Checklist:
- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anjali-dhanuka** [comment]
@prachi @abhishekarya286 @kamsuri @ramitsawhney @tapaswenipathak @Tony_tonythomas01 Please review.

**Comment by kamsuri** [comment]
By removing unique constraint you can make two events of same name but how will you differentiate between them? In #657, the suggested method is to introduce event-id and make it as primary key such that every event is uniquely defined from it's id and not name.

**Comment by anjali-dhanuka** [comment]
@kamsuri There exists a primary key for events already. Thus I have removed the unique constraint on name for the events
image
.

**Comment by kamsuri** [comment]
Alright, my bad. I haven't seen that, as primary key exists then it's fine.

**Comment by abhishekarya286** [comment]
LGTM.

**Comment by anjali-dhanuka** [comment]
@prachi1210 @tapasweni-pathak @tonythomas01 Can u please merge this?

**Pull request merged**
