### PR TITLE
Fix start date issue for create event #299

### PR DESCRIPTION
**Pull request by shoaib-s**
Users were allowed to create an event for a date in the past.
Change to not allow user to set a date in the past for create event.

### CODE REVIEW

**Comment by shoaib1987** [comment]
@tapasweni-pathak will it be possible for you to review and merge this change?

**Comment by tapasweni-pathak** [comment]
@shoaib1987 Your change fixes the issue for create event, but if I try to edit the created event and change the start date one day before today, it saves the event. Can you please look into this and fix it?

**Comment by shoaib1987** [comment]
@tapasweni-pathak thank you. Sure, I will.

**Comment by tapasweni-pathak** [comment]
@shoaib1987 Did you get the time to fix the issue in this pull request?

**Comment by shoaib1987** [comment]
@tapasweni-pathak I realized that changes made to fix this issue does not fix it(removed previously taken buffer of 1 day). A right way to fix this issue is to add timezone functionality. Current code checks date and time against UTC, this allows user to Create/Edit an event with past date. 
User should be able to select a valid date as per the venue(country, city). I can think of 2 ways to implement this 1.find the timezone based on a country and a city entered by user(this will be little challenging for various practical reasons) 2. provide drop down list to user to select a country and a city to set the specific timezone. Please let me know what your thoughts on this? If anyone has expertise wrt timezone then any help will be appreciated.

**Comment by tapasweni-pathak** [comment]
> I realized that changes made to fix this issue does not fix it(removed previously taken buffer of 1 day). A right way to fix this issue is to add timezone functionality. Current code checks date and time against UTC, this allows user to Create/Edit an event with past date. 
User should be able to select a valid date as per the venue(country, city). I can think of 2 ways to implement this 1.find the timezone based on a country and a city entered by user(this will be little challenging for various practical reasons) 2. provide drop down list to user to select a country and a city to set the specific timezone. Please let me know what your thoughts on this? If anyone has expertise wrt timezone then any help will be appreciated.

So it resolves to, providing the feature of timezone to the users. We need to detect the timezone. Can you please raise an issue explaining the problems that are occurring as we are using UTC by default?

I didn't get how 2 is different from 1 in terms of implementation. Can you explain 2 a bit more?

I am closing this pull request then. Feel free to reopen if needed.

**Pull request closed without merging**
