### PR TITLE
Internationalization and localization support added

### LINKED ISSUE #635: Internationalization and localization
## Description
From first glance I noticed that the application renders content only in English. The goal of internationalization and localization is to allow a single Web application to offer its content in two or more languages and formats tailored to the audience.

### LINKED ISSUE #642: Internationalization and localization
## Description
As a user, we can try to use the two available languages English and French by doing localhost/fr-fr or /en-us. Both gives errors.
( I am reopening a closed issue with the correct template)
## Mocks
translation

## Acceptance Criteria
- [ ] The internationalization and translations should work.

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
0.5 hour

Tag - beginner/intermediate .

### PR DESCRIPTION
**Pull request by sammy1997**
# Description
The internationalization and localization for 2 languages - English and French was added. The URLs updated accordingly.

Fixes #642 

# Type of Change:
- Code
- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Localization and internationalization working. Here are the snaps : 
englis
french

# Checklist:
- [x] My PR follows the style guidelines of this project
- [x] Any dependent changes have been merged 
- [x] My changes generate no new warnings 
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sammy1997** [comment]
@prachi1210 Please review this.

**Comment by abhishekarya286** [comment]
@sammy1997, Please provide a description.
Don't tag admins in the PR itself. If you want a review for your PR, comment separately and tag admins/mentors

**Comment by abhishekarya286** [comment]
@sammy1997. The code seems fine to me. Thanks for your contribution.
@prachi1210, In the file django.po, we don't have some translations available right now. For example, None on volunteer Sign Up page
image

But, I think for this PR, we just want that we should be able to see the translations when the user accesses the `/fr-fr/` or `/en-us/`. Right?

**Comment by sammy1997** [comment]
Thanks @abhishekarya286 . @prachi1210 @tapasweni-pathak @MeepyMay Please merge this if it's ok.

**Comment by sammy1997** [comment]
@abhishekarya286 I have re-based the branch, so as to remove the merge commits.

**Comment by abhishekarya286** [comment]
**LGTM**. Thanks for contributing. @prachi1210, please merge this one.

**Pull request merged**
