### PR TITLE
Gsoc18 infra commits

### PR DESCRIPTION
**Pull request by anjali-dhanuka**
# Description
Gsoc18 infra commits

# Type of Change:
- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anjali-dhanuka** [comment]
Hi @abhishekarya286 @ayushgarg1804 @kamsuri @nida Please merge this, so that I can rebase all my PRs.

**Comment by abhishekarya286** [comment]
Travis is failing for this one. Start the build again. May be that will resolve it.

**Comment by anjali-dhanuka** [comment]
It is passing now @abhishekarya286

**Comment by abhishekarya286** [comment]
Merging this

**Pull request merged**
