### PR TITLE
Dropdown menu for job and modified position of error message in admin report

### PR DESCRIPTION
**Pull request by softcoder32**
@tapasweni-pathak , please review,

### CODE REVIEW

**Comment by tapasweni-pathak** [comment]
@softcoder32 Can you please open a related issue and reference in this PR?

**Comment by softcoder32** [comment]
@tapasweni-pathak , this pull request solves the issues #283  and #276

**Comment by tapasweni-pathak** [comment]
@softcoder32 Please resolve conflicts and rebase.

**Comment by tapasweni-pathak** [comment]
@softcoder32 Can you please resolve conflicts and rebase?

**Comment by tapasweni-pathak** [comment]
I am closing this, reopen when rebased/resolved.

**Pull request closed without merging**
