### PR TITLE
Restrict start date and end dates of event to upcoming ones

### LINKED ISSUE #651: Previous dates available as Start and End dates of an event.
## Description
As an admin,
When I create an event I'm able to select previous dates as the Start and End date of the event. Even though the user is not able to finally create the event because an error message is shown. But I should not be able to select previous dates for the event.

## Mocks
screen shot 2018-03-05 at 8 06 15 pm

### Update [Required]
- [ ] Admin should not be able to select previus dates as Start or End dates for an event.
### Enhancement to Update [Optional]
- [ ] [LIST ITEMS]

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
1 hours

### PR DESCRIPTION
**Pull request by anjali-dhanuka**
# Description
The administrator can only select the upcoming or today's date as start and end dates while creating an event.

Fixes #651 

# Type of Change:
- Code

**Code/Quality Assurance Only**
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
screenshot from 2018-03-06 02-48-45

# Checklist:
- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [x] I have commented my code or provided relevant documentation, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by anjali-dhanuka** [comment]
@tapasweni-pathak @tonythomas01 @prachi1210 Please review.

**Comment by ramitsawhney27** [comment]
Looks good to merge.

**Comment by abhishekarya286** [comment]
Hi Anjali, It's not working on my machine.

**Comment by anjali-dhanuka** [comment]
@abhishekarya286 are you getting any error. If so can you share some screenshots.

**Comment by abhishekarya286** [comment]
Yesterday, it was not working. But, right now it is. **LGTM**. Thanks for your contribution. @prachi1210, Please merge this.

**Pull request merged**
